services:
  - type: web
    name: thriftcusat
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn ecommerce.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce.settings_prod
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECURE_SSL_REDIRECT
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: thriftcusat_db
          property: connectionString
    
databases:
  - name: thriftcusat_db
    databaseName: thriftcusat
    user: thriftcusat
    plan: free 